### ISSUE TITLE
Examples look for files in local directory

### ISSUE THREAD

**Issue by WillJRoper** [flaresimulations/synthesizer#218]
Some of the cloudy examples fail with errors like this:
```Traceback (most recent call last):
  File "/Users/willroper/Documents/University/Synthesizer/synthesizer/examples/cloudy/read_lines.py", line 13, in <module>
    cloudy_ids, blends, wavelengths, intrinsic, emergent = read_lines(
  File "/Users/willroper/Documents/University/Synthesizer/synthesizer-env/lib/python3.10/site-packages/synthesizer/cloudy.py", line 382, in read_lines
    wavelengths, cloudy_ids, intrinsic, emergent = np.loadtxt(
  File "/Users/willroper/Documents/University/Synthesizer/synthesizer-env/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1318, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/Users/willroper/Documents/University/Synthesizer/synthesizer-env/lib/python3.10/site-packages/numpy/lib/npyio.py", line 955, in _read
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/Users/willroper/Documents/University/Synthesizer/synthesizer-env/lib/python3.10/site-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/Users/willroper/Documents/University/Synthesizer/synthesizer-env/lib/python3.10/site-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /Users/stephenwilkins/Dropbox/Research/data/synthesizer/cloudy//bpass-2.2.1-bin_chabrier03-0.1,100.0_cloudy/0_7.lines not found.
sps_grid bpass-2.2.1-bin_chabrier03-0.1,300.0
```

Where they are looking for directories on @stephenmwilkins's machine. These examples should either be moved if they are too specific or a test version of the files provided.

**Comment by WillJRoper** [comment]
Not isolated to cloudy. There are also FLARES data paths in `flares.py`:
```
_grid = grid.Grid(f'../../synthesizer_data/grids/bc03_chabrier03.h5')

region = '00'
tag = '010_z005p000'
_f = '/cosma7/data/dp004/dc-love2/codes/flares/data/flares.hdf5'
```

**Comment by stephenmwilkins** [comment]
Yes, this probably needs some more test data creating. The current test grid is too low resolution to run through cloudy.
