### ISSUE TITLE
galaxy.get_images_flux breaks for certain values of limit_to

### ISSUE THREAD

**Issue by tHarvey303** [flaresimulations/synthesizer#791]
The `get_images_flux` method of Galaxy (for particle galaxies at least) has an argument called `limit_to` which allows you to only generate images for certain SED outputs. If set to e.g. 'total', to produce a flux image considering all model components only, the method will crash because it can't find the dust_emission or emergent spectra. (The two components it has to sum to produce the 'total' emission. If left at the default of None, the images will be produced successfully. 

```
Traceback (most recent call last):
  File "/nvme/scratch/work/tharvey/EXPANSE/scripts/run_mock_galaxies.py", line 114, in <module>
	mock_galaxy = MockResolvedGalaxy.init(
  File "/nvme/scratch/work/tharvey/EXPANSE/src/EXPANSE/ResolvedGalaxy.py", line 11089, in init
	return cls.init_mock_from_synthesizer(
  File "/nvme/scratch/work/tharvey/EXPANSE/src/EXPANSE/ResolvedGalaxy.py", line 10527, in init_mock_from_synthesizer
	imgs = gal.get_images_flux(
  File "/nvme/scratch/work/tharvey/synthesizer/synthesizer/src/synthesizer/base_galaxy.py", line 1151, in get_images_flux
	images = emission_model._get_images(
  File "/nvme/scratch/work/tharvey/synthesizer/synthesizer/src/synthesizer/units.py", line 667, in wrapped
	return func(*args, **kwargs)
  File "/nvme/scratch/work/tharvey/synthesizer/synthesizer/src/synthesizer/emission_models/base_model.py", line 2843, in _get_images
	raise e
  File "/nvme/scratch/work/tharvey/synthesizer/synthesizer/src/synthesizer/emission_models/base_model.py", line 2829, in _get_images
	images = self._combine_images(
  File "/nvme/scratch/work/tharvey/synthesizer/synthesizer/src/synthesizer/emission_models/operations.py", line 1103, in _combine_images
	raise exceptions.MissingSpectraType(
synthesizer.exceptions.MissingSpectraType: The following models weren't saved when generating spectra: ['dust_emission', 'emergent']
To make an image for total these must be saved.
```

Interestingly, if you set it to emergent or dust_emission, it will also crash because the method can only ever return the image with the emission_model.label key - i.e 'total' in this case with a Pacman emission model.

```

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[17], line 212
    208     img_fig = plot_images(images, filters = filters, fig = img_fig)
    210     return fig
--> 212 imgs = make_images(gal)
    214 psf_imgs = apply_psf(imgs)
    216 noisy_imgs = apply_noise(psf_imgs)

Cell In[17], line 105
    103 print(emission_model.label)
    104 # Get the image
--> 105 imgs = gal.get_images_flux(
    106     resolution,
    107     fov=width,
    108     img_type=img_type,
    109     limit_to="emergent",
    110     emission_model=emission_model,
    111     kernel=kernel_data,
    112     kernel_threshold=1,
    113 )
    115 if psfs is not None:
    116     # Apply the PSFs
    117     psf_imgs = imgs.apply_psfs(psfs)

File /nvme/scratch/work/tharvey/synthesizer/synthesizer/src/synthesizer/base_galaxy.py:1187, in BaseGalaxy.get_images_flux(self, resolution, fov, emission_model, img_type, kernel, kernel_threshold, nthreads, limit_to)
   1182         raise KeyError(
   1183             f"Unknown emitter in emission model. ({model.emitter})"
   1184         )
   1186 # Return the image at the root of the emission model
-> 1187 return images[emission_model.label]

KeyError: 'total'

```

I'm using the latest version of Synthesizer. I can work round this behaviour so it is not urgent but I suspect limit_to is not working as desired in these cases?

**Comment by tHarvey303** [comment]
Resolved in #797
